directories:
  output: dist-launcher
  buildResources: public/images
appId: com.swingcity.launcher
productName: SwingCity V2 Launcher
files:
  - filter:
      - launcher/**/*
      - server.js
      - public/**/*
      - config/**/*
      - services/**/*
mac:
  target:
    - dmg
  icon: public/images/swingcity-logo.png
electronVersion: 37.4.0
